### PR TITLE
Update to beta ember-power-select

### LINKED ISSUE #14: Update to EPS 1.0.0-alpha

### PR DESCRIPTION
**Pull request by jesseditson**
Fixes #14:
- migrates to latest EPS API (
- Extend component rather than re-implementing it
- Add support for showing options on hover
- Simplify dirty detection on input value
- Add test for new option
- Add some demos to dummy app

I took some liberties with the code, but kept the old tests, which continue to pass. The only added functionality is the ability to pass `showOptions`, which causes the list to show on focus if `options` are provided (therefore providing a simple filtering typeahead instead of an async one). I added a test to cover this use case.

This likely needs a review to make sure I'm matching style properly, but I tested it pretty thoroughly (via the new views in the dummy app).

This also probably wants a minor/major version bump because of the breaking EPS dependency, but the API is identical so that's your call.

Here's a demo of the functionality:

### CODE REVIEW

**Comment by sivakumar-kailasam** [comment]
@cibernox I've been using @jesseditson's branch on my app. Works as expected for me. Hope this gets merged and we get a release 😄

**Comment by cibernox** [comment]
Ok, I'm going to pull these changes and review it now. 

For opening on focus I typically recommend users to use the `onfocus=(action "openIfIFeelLike")`. and let the users decide what to do when it gets the focus.
I do that to keep the api of the component minimal yet make it flexible enough.

That said, that's Ember Power Select rules, this component doesn't need to adhere to the same principle of being as low-level as possible, so one option to `openOnFocus` might be ok.

**Comment by cibernox** [comment]
For the record, I've been on holidays until Monday, that's why it took soo long 😓

**Comment by sivakumar-kailasam** [comment]
😄 hope you had a good time @cibernox

**Comment by cibernox** [comment]
In the review I found a couple errors. In particular, when you search for a string that doesn't give any results and the components. Given that this component had quite a lot of changes not-related with the update to 1.0.0, I did another PR that contains no changes in functionality, just the minimum changes to make it work.

It has been released on 0.4.1.

I added one example using a non-asynchonous search to the application.hbs.

@jesseditson can you check if it works for you (openOnFocus aside)?

**Comment by jesseditson** [comment]
Thanks! I'll take a peek at this when I get a moment and get it shored up & rebases.

**Pull request closed without merging**
