### PR TITLE
Make sure onKeyDown returns false if action returns false

### PR DESCRIPTION
**Pull request by gtb104**
The issue was that a user defined `onkeydown` action that returned `false` would not flow back to power-select. So, there was no way of preventing the default behavior of power-select's `onKeydown` handler.

This PR fixes that by expressly looking for an action that returns `false` and returning `false` itself. If there was no action supplied, or the action returned a value other than `false`, it continues along its previous path of execution.

### CODE REVIEW

**Comment by gtb104** [comment]
Looks like the `.travis.yml` is out of date or something as it doesn't align with the `ember-power-select` addon. I don't really know Travis, but I can add what needs to change into this PR if someone clues me in.

**Comment by cibernox** [comment]
Hey thanks! Code looks good and the change makes total sense. Maybe can help with travis later (or this weekend) if it's stubborn.

**Comment by gtb104** [comment]
I'm trying to figure it out myself for now. If I can't make any headway tonight, I'll definitely take your offer for help! 😄

**Comment by gtb104** [comment]
Yay! The tests have passed. I'm not sure you want all the changes that I made to get them to pass, so I'm open to backing some out as long as this PR passes and gets pushed through. I'm dependent upon this change for a feature I'm currently working, so I'm anxious to get it merged.

**Comment by gtb104** [comment]
Any thought on this PR?

**Comment by gtb104** [comment]
I know that you're busy with your new addition ( congratulations! ), so I'm wondering if there's anyone else who could review this PR?

**Comment by cibernox** [comment]
Thanks! I'll find time to release a new version later today. If I forget ping me tomorrow

**Comment by gtb104** [comment]
Ping! :-)

**Comment by cibernox** [comment]
@gtb104 pong!

v0.7.4

**Pull request merged**
